import type { ChatMessage, User, Workout } from './types'

export const CURRENT_USER_ID = 'u_danny'

function isoOffset(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export const SEED_USERS: User[] = [
  {
    id: CURRENT_USER_ID,
    name: 'Danny Rivera',
    username: 'dannylifts',
    bio: 'Chasing a 405 deadlift. Always down to train. 🏋️',
    homeGym: 'Crunch Fitness',
    city: 'Boynton Beach',
    favoriteSplit: 'Push / Pull / Legs',
    hue: 210,
    avatar: '/avatars/danny.png',
    isPrivate: false,
    gallery: ['/gallery/danny-1.png', '/gallery/danny-2.png', '/gallery/danny-3.png'],
    reliability: 96,
    streak: 12,
  },
  {
    id: 'u_mike',
    name: 'Mike Chen',
    username: 'mikegetswole',
    bio: 'Leg day enthusiast. Never skips.',
    homeGym: 'Crunch Fitness',
    city: 'Boynton Beach',
    favoriteSplit: 'Arnold Split',
    hue: 150,
    avatar: '/avatars/mike.png',
    isPrivate: false,
    gallery: ['/gallery/mike-1.png', '/gallery/danny-2.png'],
    reliability: 88,
    streak: 7,
  },
  {
    id: 'u_jake',
    name: 'Jake Morales',
    username: 'jakemo',
    bio: 'Powerlifter. Coffee, then chalk.',
    homeGym: 'EOS Fitness',
    city: 'Wellington',
    favoriteSplit: 'Upper / Lower',
    hue: 25,
    avatar: '/avatars/jake.png',
    isPrivate: false,
  },
  {
    id: 'u_sarah',
    name: 'Sarah Kim',
    username: 'sarahruns',
    bio: 'Marathon training + strength. Cardio queen.',
    homeGym: 'LA Fitness',
    city: 'Boca Raton',
    favoriteSplit: 'Run + Full Body',
    hue: 330,
    avatar: '/avatars/sarah.png',
    isPrivate: true,
    gallery: ['/gallery/sarah-1.png'],
    reliability: 91,
    streak: 5,
  },
  {
    id: 'u_andre',
    name: 'Andre Willis',
    username: 'dredunks',
    bio: 'Hoops most nights. Come run with us.',
    homeGym: 'The Yard',
    city: 'Delray Beach',
    favoriteSplit: 'Basketball + Conditioning',
    hue: 275,
    avatar: '/avatars/andre.png',
    isPrivate: false,
  },
  {
    id: 'u_lena',
    name: 'Lena Torres',
    username: 'lenacrossfit',
    bio: 'CrossFit coach. WOD warrior.',
    homeGym: 'EOS Fitness',
    city: 'Wellington',
    favoriteSplit: 'CrossFit',
    hue: 190,
    avatar: '/avatars/lena.png',
    isPrivate: false,
    gallery: ['/gallery/lena-1.png', '/gallery/danny-3.png'],
    reliability: 94,
    streak: 9,
  },
]

export function seedWorkouts(): Workout[] {
  return [
    {
      id: 'w1',
      hostId: 'u_mike',
      gym: 'Crunch Fitness',
      city: 'Boynton Beach',
      lat: 26.5285,
      lng: -80.0846,
      date: isoOffset(0),
      time: '19:00',
      types: ['Legs', 'Core'],
      notes: 'Heavy squats today. Bring a spotter energy.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: ['u_mike', 'u_lena'],
      recurring: 'weekly',
    },
    {
      id: 'w2',
      hostId: 'u_jake',
      gym: 'EOS Fitness',
      city: 'Wellington',
      date: isoOffset(0),
      time: '21:30',
      types: ['Chest', 'Arms'],
      notes: 'Late night pump. Bench focus.',
      maxParticipants: 3,
      visibility: 'public',
      attendees: ['u_jake'],
      recurring: 'none',
    },
    {
      id: 'w3',
      hostId: 'u_andre',
      gym: 'The Yard',
      city: 'Delray Beach',
      lat: 26.4615,
      lng: -80.0728,
      date: isoOffset(0),
      time: '20:00',
      types: ['Basketball'],
      notes: 'Pickup runs, first to 5 wins. 3 spots then we rotate.',
      maxParticipants: 3,
      visibility: 'public',
      attendees: ['u_andre', 'u_sarah', 'u_lena'],
      recurring: 'none',
    },
    {
      id: 'w4',
      hostId: 'u_sarah',
      gym: 'LA Fitness',
      city: 'Boca Raton',
      date: isoOffset(1),
      time: '06:30',
      types: ['Running', 'Cardio'],
      notes: 'Easy 5 miler before work. Slow pace welcome.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: ['u_sarah'],
      recurring: 'daily',
    },
    {
      id: 'w5',
      hostId: 'u_lena',
      gym: 'EOS Fitness',
      city: 'Wellington',
      date: isoOffset(2),
      time: '18:00',
      types: ['CrossFit', 'HIIT'],
      notes: 'Partner WOD. Scaling available.',
      maxParticipants: 3,
      visibility: 'public',
      attendees: ['u_lena'],
      recurring: 'weekly',
    },
    {
      id: 'w6',
      hostId: CURRENT_USER_ID,
      gym: 'Crunch Fitness',
      city: 'Boynton Beach',
      date: isoOffset(4),
      time: '22:00',
      types: ['Back'],
      notes: 'Pull day. Deadlifts + rows.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: [CURRENT_USER_ID, 'u_mike'],
      recurring: 'weekly',
    },
    {
      id: 'w7',
      hostId: CURRENT_USER_ID,
      gym: 'Crunch Fitness',
      city: 'Boynton Beach',
      date: isoOffset(0),
      time: '18:30',
      types: ['Push', 'Shoulders'],
      notes: 'Chest + shoulders + tris. Come thru.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: [CURRENT_USER_ID],
      recurring: 'weekly',
    },
    {
      id: 'w8',
      hostId: CURRENT_USER_ID,
      gym: 'Crunch Fitness',
      city: 'Boynton Beach',
      date: isoOffset(2),
      time: '19:00',
      types: ['Pull', 'Arms'],
      notes: 'Back + biceps. Volume day.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: [CURRENT_USER_ID, 'u_jake'],
      recurring: 'weekly',
    },
    {
      id: 'w9',
      hostId: CURRENT_USER_ID,
      gym: 'Crunch Fitness',
      city: 'Boynton Beach',
      date: isoOffset(6),
      time: '09:00',
      types: ['Legs'],
      notes: 'Weekend leg day. Squats + accessories.',
      maxParticipants: 3,
      visibility: 'friends',
      attendees: [CURRENT_USER_ID],
      recurring: 'weekly',
    },
  ]
}

export function seedMessages(): ChatMessage[] {
  const now = Date.now()
  return [
    {
      id: 'm1',
      workoutId: 'w1',
      userId: 'u_mike',
      text: 'Pulling up around 6:55, parking in the back lot 🅿️',
      createdAt: now - 1000 * 60 * 42,
    },
    {
      id: 'm2',
      workoutId: 'w1',
      userId: 'u_lena',
      text: 'Copy. I’ll grab us a squat rack.',
      createdAt: now - 1000 * 60 * 38,
    },
    {
      id: 'm3',
      workoutId: 'w6',
      userId: 'u_mike',
      text: 'Deadlift day let’s gooo',
      createdAt: now - 1000 * 60 * 60 * 5,
    },
    // Public community channel (workoutId: 'community')
    {
      id: 'c1',
      workoutId: 'community',
      userId: 'u_andre',
      text: 'Anyone runs hoops at The Yard on weekends? Trying to get a 3s league going 🏀',
      createdAt: now - 1000 * 60 * 60 * 3,
    },
    {
      id: 'c2',
      workoutId: 'community',
      userId: 'u_sarah',
      text: 'Morning run crew — 6am loop around the lake tomorrow if anyone wants in!',
      createdAt: now - 1000 * 60 * 96,
    },
    {
      id: 'c3',
      workoutId: 'community',
      userId: 'u_jake',
      text: 'PSA: EOS Wellington just got new hack squat machines. Legs never felt so good.',
      createdAt: now - 1000 * 60 * 54,
    },
    {
      id: 'c4',
      workoutId: 'community',
      userId: 'u_lena',
      text: 'Looking for a spotter for heavy bench Thursdays. Boynton area 💪',
      createdAt: now - 1000 * 60 * 18,
    },
  ]
}

/** Channel id used for the public community chat */
export const COMMUNITY_CHANNEL_ID = 'community'

/** Who the current user follows */
export const SEED_FOLLOWING = ['u_mike', 'u_jake', 'u_sarah', 'u_andre', 'u_lena']
/** Who follows the current user */
export const SEED_FOLLOWERS = ['u_mike', 'u_jake', 'u_andre', 'u_lena']
